# Default values for generic-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# DaemonSet or Deployment or StatefulSet
configMaps:
  create: false
  data:
    SAMPLE_CONFIG: "sample-config"

secrets:
  create: false
  data:
    SAMPLE_PASSWORD: "sample-secret"

# volumeMounts:
#   - name: config-mount
#     mountPath: /app/config

# volumes:
#   - name: config-mount
#     configMap:
#       name: config

serviceHostNetwork:
  enabled: false
  policy: ClusterFirstWithHostNet

serviceHeadless:
  enabled: false
  # annotation: {}
  # ports:
  #   - name: sample1-service-port
  #     protocol: TCP
  #     port: 80
  #     targetPort: 80
  #   - name: sample2-service-port
  #     protocol: TCP
  #     port: 8080
  #     targetPort: 8080
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  rules:
    - host: a.example.com
      http:
        paths:
          - path: /
            backend:
              - servicePort: 80
          - path: /api
            backend:
              - servicePort: 8080
    - host: b.example.com
      http:
        paths:
          - path: /
            backend:
              - servicePort: 80
  tls: {}
  #  - hosts:
  #    - a.example.com
  #    - b.example.com
  #    secretName: wildcard.example.com
