{{- if .Values.ingress }}
{{- if .Values.ingress.enabled }}
{{- $fullName := include "generic-deployment.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "generic-deployment.name" . }}
    helm.sh/chart: {{ include "generic-deployment.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.ingress.annotations }}
    # ingress:
    #   annotations:
    #     kubernetes.io/ingress.class: nginx
    #     nginx.ingress.kubernetes.io/limit-connections: 100
    #     nginx.ingress.kubernetes.io/limit-rps: 100
    #     nginx.ingress.kubernetes.io/proxy-connect-timeout: 120
    #     nginx.ingress.kubernetes.io/proxy-send-timeout: 120
    #     nginx.ingress.kubernetes.io/proxy-read-timeout: 120
    #   rules:
    #     - host: app.example.com
    #       http:
    #         paths:
    #           - path: /
    #             backend:
    #               servicePort: 80
    #           - path: /review
    #             backend:
    #               servicePort: 80
    #   tls:
    #     - hosts:
    #       - app1.example.com
    #       - app2.example.com
    #       secretName: wildcard.example.com
    #     - hosts:
    #       - app1.example.org
    #       secretName: app1.example.org
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.rules }}
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .http.paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .backend.servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
